/*
-- Query: SELECT * FROM quick_notes.documents
LIMIT 0, 1000

-- Date: 2024-02-25 19:09
*/
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (1,1,'Första dokument','<p style=\"text-align: left;\">Lorem ipsum</p>\n<p style=\"text-align: left;\"><span style=\"color: rgb(22, 145, 121);\">oooooch lite till</span></p>\n<p style=\"text-align: left;\"><span style=\"color: rgb(132, 63, 161);\">vad s&auml;gs om en 3e f&auml;rg?</span></p>\n<p style=\"text-align: left;\"><span style=\"color: rgb(35, 111, 161); background-color: rgb(251, 238, 184);\">och en 4e?</span></p>\n<p style=\"text-align: left;\">&nbsp;</p>\n<p style=\"text-align: left;\"><span style=\"color: rgb(35, 111, 161); background-color: rgb(45, 194, 107);\">hahahahahha</span></p>\n<p style=\"text-align: left;\">&nbsp;</p>','2024-02-19 15:46:50','2024-02-23 19:57:24',NULL);
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (2,1,'Ett editerat dokument','<p style=\"text-align: center;\">Lorrem ippsum</p>\n<p style=\"text-align: center;\"><span style=\"color: rgb(224, 62, 45);\">&aring;&aring;h hj&auml;lp?</span></p>\n<p style=\"text-align: center;\"><span style=\"color: rgb(45, 194, 107);\">jaha?</span></p>\n<p style=\"text-align: center;\"><span style=\"color: rgb(45, 194, 107);\"><span style=\"background-color: rgb(230, 126, 35);\">gaahaaaaaa</span></span></p>\n<p style=\"text-align: center;\"><span style=\"color: rgb(132, 63, 161); background-color: rgb(0, 0, 0);\"><span style=\"background-color: rgb(191, 237, 210);\">WARUM?</span></span></p>\n<p style=\"text-align: center;\"><span style=\"color: rgb(132, 63, 161); background-color: rgb(0, 0, 0);\"><span style=\"background-color: rgb(191, 237, 210);\">jaha?</span></span></p>\n<p style=\"text-align: center;\">&nbsp;</p>\n<p style=\"text-align: center;\">&nbsp;</p>','2024-02-19 15:52:35','2024-02-23 12:42:00',NULL);
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (3,3,'First document','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','2024-02-19 15:53:06','2024-02-19 15:53:06',NULL);
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (4,3,'Second document','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','2024-02-19 15:53:19','2024-02-19 15:53:19',NULL);
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (5,1,'Första dokumentet skapat?','<p>t<span style=\"background-color: rgb(236, 202, 250);\">joohooooooooooo!!!!!</span><br>?</p>','2024-02-22 16:33:11','2024-02-22 16:34:10',NULL);
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (6,1,'andra skapade dokumentet','<p>Nu b&ouml;rjar detta k&auml;nnas lite skakigt &auml;nd&aring;!</p>\n<p>&nbsp;</p>\n<p><span style=\"color: rgb(35, 111, 161);\">Men vi f&aring;r v&auml;l f&ouml;rs&ouml;ka h&aring;lla galenskaperna borta!</span></p>','2024-02-22 16:41:31','2024-02-22 16:41:31',NULL);
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (7,10,'Mans mansplaining','<p>\"M&ouml;t Mans M&aring;nsson, mannen som inte bara har en &aring;sikt om allt, utan ocks&aring; tror att hans &aring;sikt &auml;r den enda som spelar roll. Han &auml;r som en encyklopedi &ouml;ver sj&auml;lv&ouml;verskattning och &ouml;verdrivet sj&auml;lvf&ouml;rtroende.\"</p>\n<p>\"<span style=\"background-color: rgb(236, 202, 250);\">Mans M&aring;nsson, mannen som tror att han kan f&ouml;rklara saker f&ouml;r dig &auml;ven n&auml;r du redan vet mer &auml;n honom. Han &auml;r som en GPS som</span> envisas med att dirigera dig till platser du redan befinner dig p&aring;.\"</p>\n<p>\"<span style=\"background-color: rgb(241, 196, 15);\">Mans M&aring;nsson &auml;r den perfekta kombinationen av &ouml;vertygande och oinformerad. Han tror att han &auml;r en guru inom alla &auml;mnen, men i verkligheten &auml;r han mer som en amat&ouml;rkock som tror att han kan l&auml;ra en Michelin-kock hur man lagar mat.\"</span></p>\n<p>\"Mans M&aring;nsson, mannen som tror att han &auml;r en hj&auml;lte f&ouml;r att han delar med sig av sina visdomsord till kvinnor. Han &auml;r som en supersoldat i sitt eget sinne, men f&ouml;r resten av v&auml;rlden &auml;r han mest en komisk karakt&auml;r.\"</p>\n<p>\"Mans M&aring;nsson, den o&ouml;vertr&auml;ffade m&auml;staren av att f&ouml;rklara saker p&aring; ett s&auml;tt som f&aring;r dig att undra om han ens lyssnar p&aring; sig sj&auml;lv. Han &auml;r som en stand-up komiker vars sk&auml;mt alltid faller platt, men han skrattar &auml;nd&aring; &aring;t dem sj&auml;lv.\"</p>','2024-02-22 19:02:15','2024-02-22 19:04:51',NULL);
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (8,1,'Titel','<p>Varf&ouml;r var bokens matematikbetyg s&aring; d&aring;ligt?</p>\n<p><span style=\"background-color: rgb(185, 106, 217);\">F&ouml;r att den alltid adderade problem!</span></p>','2024-02-23 16:58:36','2024-02-23 16:58:36',NULL);
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (9,1,'Orangeri','<p><span style=\"background-color: rgb(230, 126, 35);\">att vi inte har n&aring;gra dokument</span></p>','2024-02-23 19:34:36','2024-02-23 20:24:44',NULL);
INSERT INTO `` (`id`,`userId`,`heading`,`content`,`created`,`lastEdited`,`softDelete`) VALUES (10,1,'notes22','<p>Det var en g&aring;ng en hammarhaj vid namn Herman, som bodde i det <span style=\"background-color: rgb(194, 224, 244);\">glittrande bl&aring;a </span>havet. Till skillnad fr&aring;n de flesta hajar hade Herman en mycket konstig avsky - han avskydde bananer! Varje g&aring;ng han simmade f&ouml;rbi en banan i havet skulle han snabbt v&auml;nda om och simma &aring;t andra h&aring;llet. Hans v&auml;nner fann det b&aring;de lustigt och f&ouml;rbryllande.</p>\n<p>En dag simmade Herman runt och letade efter sitt favoritbyte n&auml;r han pl&ouml;tsligt st&ouml;tte p&aring; en stor klunga bananer som fl&ouml;t i vattnet. Han ryggade tillbaka och skakade p&aring; huvudet i f&ouml;rakt. \"Usch, bananer!\" mumlade han f&ouml;r sig sj&auml;lv och simmade iv&auml;g s&aring; fort han kunde.</p>\n<p>Herman f&ouml;rs&ouml;kte undvika bananerna s&aring; gott det gick, men ibland var de &ouml;verallt. Hans v&auml;nner b&ouml;rjade reta honom och kalla honom \"Herman, banan-fobikern\". Trots deras sk&auml;mt kunde Herman inte &ouml;vervinna sin avsky f&ouml;r <span style=\"background-color: rgb(241, 196, 15);\">bananer.</span></p>\n<p>Trots hans avsky f&ouml;r bananer var Herman fortfarande en mycket &auml;lskad och respekterad hammarhaj i det bl&aring;a havet. Och &auml;ven om bananer var hans st&ouml;rsta fobi, hindrade det honom inte fr&aring;n att njuta av sitt liv bland korallreven och fiskarna i sitt vackra hem.</p>','2024-02-23 19:49:53','2024-02-23 20:22:53',NULL);
